### ISSUE TITLE
[Enhancement]: migrate milvus 2.x  cluster mode  from docker-compose to milvus 2.x  cluster mode on kubernetes

### ISSUE THREAD

**Issue by MayurDuduka** [zilliztech/milvus-migration#67]
### What would you like to be added?

- **source:** Milvus version on docker-compose:  v2.3.1 (cluster mode)
- **destination:** Milvus version on Kubernetes:  v2.3.1 (cluster mode)

**We want to migrate all the collections to Kubernetes Milvus from Milvus docker-compose.**

Can someone please assist with the steps here?

Thanks

### Why is this needed?

- **source:** Milvus version on docker-compose:  v2.3.1 (cluster mode)
- **destination:** Milvus version on Kubernetes:  v2.3.1 (cluster mode)

**We want to migrate all the collections to Kubernetes Milvus from Milvus docker-compose.**

Can someone please assist with the steps here?

Thanks

**Comment by wenhuiZilliz** [comment]
@MayurDuduka  now supported milvus2x -> milvus2x migration: https://github.com/zilliztech/milvus-migration/blob/main/README_2X.md
