### ISSUE TITLE
[LICENSE] please mention sbinet/npyio

### ISSUE THREAD

**Issue by sbinet** [zilliztech/milvus-migration#73]
### Current Behavior

currently, the file under `milvus-migration/core/transform/numpy/convert.go` contains huge swath of (almost not modified) code coming from:

- https://github.com/sbinet/npyio/blob/main/npy/npy.go
- https://github.com/sbinet/npyio/blob/main/npy/writer.go

the LICENSE of `sbinet/npyio` allows for code copying (it's BSD3) but, as stated in the LICENSE file:
https://github.com/sbinet/npyio/blob/main/LICENSE
```
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
```

please add the following blurb to your `numpy/convert.go` file:

```go
// Copyright 2016 The npyio Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
```
or somewhere else relevant.

thanks a lot.

@Thomas-HuWei @xiaocai2333

### Expected Behavior

correct licensing attributions.

**Comment by xiaofan-luan** [comment]
Sure thing.
We will definitely add it back

**Comment by Thomas-HuWei** [comment]
@sbinet  Thanks for your issue, I've add the LICENSE comment to the file: 
https://github.com/zilliztech/milvus-migration/pull/74/files
