### ISSUE TITLE
[Bug]: Where to add partition tag?

### ISSUE THREAD

**Issue by uniyushu** [zilliztech/milvus-migration#84]
### Current Behavior

In Milvus-migration/testfiles/milvus1x/test1w/meta.json, I can't find the partition tag, but my data has a partition tag,
how do I add this tag in meta.json?
```
{
    "collections": [
        {
            "collection": "test1w",
            "metric": 1,
            "rows": 10000,
            "dim": 256,
            "segments": [
                {
                    "collection": "test1w",
                    "segment": "1678354366132931000",
                    "dim": 256,
                    "rows": 10000,
                    "fileSize": 10320000
                }
            ]
        }
    ],
    "rows": 10000
}

```

```
{
    "collections": [
        {
            "collection": "test1w",
            "metric": 1,
            "rows": 10000,
            "dim": 256,
            "partitions": "total",    #
            "partition_tag": "total", # 
            "tag": "total",  # 
            "partition": "total",   # which name is the right answer
            "segments": [
                {
                    "collection": "test1w",
                    "segment": "1678354366132931000",
                    "dim": 256,
                    "rows": 10000,
                    "fileSize": 10320000
                }
            ]
        }
    ],
    "rows": 10000
}

```

Is partition tag supported?

### Expected Behavior

transfer milvus1x to milvus2x

**Comment by xiaofan-luan** [comment]
the API style of partition is very different. 
https://milvus.io/docs/manage-partitions.md

and partition search 
https://milvus.io/docs/single-vector-search.md#Partition-search

**Comment by uniyushu** [comment]
> the API style of partition is very different. https://milvus.io/docs/manage-partitions.md
> 
> and partition search https://milvus.io/docs/single-vector-search.md#Partition-search

[meta.json](https://github.com/zilliztech/milvus-migration/blob/main/testfiles/milvus1x/test1w/meta.json) This example without partition tag, please provide one with a partition tag.

**Comment by Thomas-HuWei** [comment]
@uniyushu 
hello，I've konwn.
Sorry that this tool not support partition now.
And I'm learning about that the different partition mechanism between milvus1.x and milvus2.x.
And it's still need some times to develop the support of partition.
